# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stopgo < Formula
  desc ""
  homepage ""
  version "0.3.1"
  license "MIT"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/jdhayford/stopgo/releases/download/v0.3.1/stopgo_0.3.1_Darwin_x86_64.tar.gz"
    sha256 "d6c65a1cb70eff1eb209069ce91010cd3dd2dbdc32c8562fa178cc2067fa5784"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/jdhayford/stopgo/releases/download/v0.3.1/stopgo_0.3.1_Linux_x86_64.tar.gz"
    sha256 "3dbefb7274b68bfa7a60d57733e828064ba641b7c9a4339fed0805272d4248bf"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/jdhayford/stopgo/releases/download/v0.3.1/stopgo_0.3.1_Linux_arm64.tar.gz"
    sha256 "1df406e97f87473b678765def655c6e4c325c38d143067d03db9bc786f98fea0"
  end

  depends_on "git"
  depends_on "zsh" => :optional

  def install
    bin.install "stopgo"
  end
end
